### ISSUE TITLE
Adição automática de cursos

### ISSUE THREAD

**Issue by ryanrpj** [mosfete/front-end-flataforma-cursos#3]
Agora com o projeto dockerizado e os cursos centralizados no diretório /data, enxergo a possibilidade do back-end escanear automaticamente este diretório e adicionar automaticamente todos os cursos (tecnicamente, sub-diretórios) que ele encontrar.

No front-end, exibir apenas um botão "Escanear cursos" que ativa essa feature e todo o trabalho pesado é feito para o usuário. Assim eliminamos a possível confusão gerada em exigir que o usuário insira manualmente o path de cada curso que ele quer adicionar.

@dragaoinvisivel faz sentido implementar essa feature?

**Comment by dragaoinvisivel** [comment]
Sim, faz sentido.

Uma coisa que também pode fazer sentido é adicionar uma função semelhante em cada curso, dando a opção de checar novamente o diretório daquele curso em especifico e adequar o que o usuário consome dele. Visto algumas pessoas deletam ou adicionam conteúdos a um determinado curso por n razões, como aproveitamento de espaço, extração de .zips e etc.
