### ISSUE TITLE
Containers não rodam em amd64/linux

### ISSUE THREAD

**Issue by dragaoinvisivel** [mosfete/front-end-flataforma-cursos#4]
Para conseguir executar na minha maquina (Windows 10 e Processador Ryzen 5) tive que fazer usar moby/buildkit:buildx-stable-1 para gerar uma imagem docker com base nas disponibilizadas por @ryanrpj. Erro que aparecia:

`The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64/v3) and no specific platform was requested`

https://stackoverflow.com/questions/66662820/m1-docker-preview-and-keycloak-images-platform-linux-amd64-does-not-match-th

**Comment by ryanrpj** [comment]
Poderia tentar novamente? Acabei de subir imagens para linux/arm64 tanto para o front-end quanto para o back-end. Não se esqueça da flag `--pull always` ao rodar `docker run` ou `docker compose up` para garantir que a nova versão das imagens será baixada. Fico no aguardo.

**Comment by ryanrpj** [comment]
Após subir imagens para a arquitetura amd64, o projeto está executando como esperado. Testado em uma máquina Linux com Ubuntu 24.04.4 LTS.
